name: First Workflow
on: workflow_dispatch
jobs:
  first-job:
    runs-on: ubantu-latest
    steps:
      - name: Print greeting
        run: echo "Hello, world!"
      - name: Done bye
        run: echo "Bye, bye"
